name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify Ubuntu version

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (using Temurin distribution for JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Gradle wrapper (if not already configured)
      - name: Set up Gradle wrapper
        run: chmod +x gradlew

      # Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleDebug

      # Debug Step: List APK output directory and verify APK
      - name: Debug - List APK Directory
        run: |
          ls -lh app/build/outputs/apk/debug/
          file app/build/outputs/apk/debug/app-debug.apk

      # Upload the APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
